spring:
  application:
    name: ms-notification-streaming

  mongodb:
    uri: mongodb://localhost:27017/wd_notification_streaming_db

logging: # Sección de logs
  level:
    "[org.springframework.web]": DEBUG # Logs detallados para web (request HTTP)
    "[org.springframework.data.mongodb]": DEBUG # Muestra las consultas que Spring Data hace a MongoDB

server:
  port: 9091
  servlet:
    context-path: /api/v3

security:
  jwt:
    secret-key: fx3VDiOxgojN6m3+9reMeoSdyPt7JOq0Zx67hKOIrHI=
    token-expiration: 900000